Step:
  step_adjustments:
    - MetricIntervalLowerBound: 0
      ScalingAdjustment: 1
    - MetricIntervalUpperBound: 0
      ScalingAdjustment: -1
Target:
  override_defaults: true
  properties:
    PolicyName: HelloWorldECSServiceApplicationTargetScalingPolicy
    ScalingTargetId:
      Ref: HelloWorldServiceECSServiceScalableTarget
    PolicyType: TargetTrackingScaling
    TargetTrackingScalingPolicyConfiguration:
      TargetValue: 0.1 # Can't be 0?
      CustomizedMetricSpecification:
        Namespace: AWS/States
        MetricName: ActivitiesScheduled
        Statistic: Sum
        Dimensions:
          - Name: ActivityArn
            Value:
              Ref: HelloWorldActivity