Step:
  step_adjustments:
    - MetricIntervalLowerBound: 0
      ScalingAdjustment: 1
    - MetricIntervalUpperBound: 0
      ScalingAdjustment: -1
Target:
  override_defaults: true
  properties:
    PolicyName: HelloWorldECSServiceApplicationTargetScalingPolicy
    ScalingTargetId:
      Ref: HelloWorldServiceECSServiceScalableTarget
    PolicyType: TargetTrackingScaling
    TargetTrackingScalingPolicyConfiguration:
      TargetValue: 0.1 # Apparently, this can't be 0, see https://docs.aws.amazon.com/autoscaling/application/APIReference/API_TargetTrackingScalingPolicyConfiguration.html
      CustomizedMetricSpecification:
        Namespace: AWS/States
        MetricName: ActivitiesScheduled
        Statistic: Sum
        Dimensions:
          - Name: ActivityArn
            Value:
              Ref: HelloWorldActivity