default:
  bucket: cumulus-test-sandbox-internal
  apiUsername: jasmine
  pdrNodeNameProviderBucket: cumulus-sandbox-pdr-node-name-provider

cumulus-sit:
  bucket: cumulus-sit-internal
  apiUsername: jasmine
  pdrNodeNameProviderBucket: cumulus-sit-pdr-node-name-provider

jl-tf:
  bucket: jl-test-integration-internal

jl-rds-tf:
  bucket: jl-test-integration-internal

vkn-tf:
  bucket: vkn-tf-internal

vkn-ci-tf:
  bucket: vkn-ci-tf-internal

np:
  bucket: npauzenga-internal

nnaga-tf:
  bucket: nnaga-internal

ecarton:
  bucket: ecarton-internal