Resources:
  Fn:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Join ['-', [!Ref StackName, task, !Var name]]
      Runtime: nodejs6.10
      Code: !Var path
      Handler: index.handler
      Role: !GetAtt [TaskExecutionRole, Arn]

  Service:
    DependsOn:
      - !ResourceName Fn
    Properties:
      DesiredCount: 1
