language: node_js

stages:
  - name: build cache
  - name: test
  - name: deploy
    if: branch = master AND tag IS present
  - name: deployment test
    if: branch = master AND tag IS present

jobs:
  include:
    - name: "Build npm cache"
      stage: build cache
      install: true
      script: ./travis-ci/build-cache.sh

    - name: "eslint"
      stage: test
      install:
        - ./travis-ci/fetch-cache.sh
        - npm install
        - npm run bootstrap-no-build
      script: ./node_modules/.bin/eslint packages/api --ext .js
    - name: "Unit tests except API"
      stage: test
      services:
        - docker
      env:
        - LOCALSTACK_HOST=127.0.0.1
        - LOCAL_ES_HOST=127.0.0.1
      install:
        - ./travis-ci/fetch-cache.sh
        - npm install
        - npm run bootstrap-no-build
        - ./travis-ci/start-local-services.sh
      script: ./node_modules/.bin/nyc ./node_modules/.bin/lerna run test --ignore @cumulus/api
    - name: "API unit tests"
      stage: test
      services:
        - docker
      env:
        - LOCALSTACK_HOST=127.0.0.1
        - LOCAL_ES_HOST=127.0.0.1
      install:
        - ./travis-ci/fetch-cache.sh
        - npm install
        - npm run bootstrap-no-build
        - ./travis-ci/start-local-services.sh
      script: ./travis-ci/run-api-unit-tests.sh
    - name: "e2e tests"
      stage: test
      services:
        - docker
      env:
        - LOCALSTACK_HOST=127.0.0.1
        - LOCAL_ES_HOST=127.0.0.1
      install:
        - ./travis-ci/fetch-cache.sh
        - npm install
        - npm run bootstrap-no-build
        - ./travis-ci/start-local-services.sh
      script: npm run e2e
    - name: "Integration tests"
      stage: test
      install:
        - ./travis-ci/fetch-cache.sh
        - npm install
        - npm run bootstrap-no-build
      script: ./travis-ci/run-integration-tests.sh

    - name: "Deploy to NPM"
      stage: deploy
      install: npm install
      script: ./travis-ci/deploy-to-npm.sh
    - name: "Deploy to Github Pages"
      stage: deploy
      install: npm install
      script: ./travis-ci/deploy-to-github-pages.sh

    - name: "Run integration tests against deployed packages"
      stage: deployment test
      install:
        - ./travis-ci/fetch-cache.sh
        - npm install
        - npm run bootstrap-no-build
      script: ./travis-ci/run-integration-tests.sh
      env:
        - DEPLOYMENT=cumulus-from-npm
