version: '3'
services:
  local:
    image: cumuluss/circleci:node-6.10
    command: start
    volumes:
      - "./packages/test-data:/home/vsftpd:ro"
      - "./.tmp-test-data:/var/www/html:ro"
      - "./.tmp-test-data:/home/user"
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
      - "3030:3030"
      - "2222:2222"
    links:
      - localstack
    depends_on:
      - localstack

  test:
    image: cumuluss/circleci:node-6.10
    volumes:
      - ".:/home/circleci/project"
      - "./packages/test-data:/home/vsftpd:ro"
      - "./.tmp-test-data:/var/www/html:ro"
      - "./.tmp-test-data:/home/user"
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
      - "3030:3030"
      - "2222:2222"
    links:
      - localstack
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    ports:
      - 4567-4582:4567-4582
      - 8080:8080