version: '2'
services:
  local:
    image: peopleperhour/dynamodb
    ports:
      - "8000:8000"
    depends_on:
      - sqs
      - elasticsearch
      - ftp
      - http

  sqs:
    image: vsouza/sqs-local
    ports:
      - "9324:9324"

  elasticsearch:
    image: elasticsearch:2.3.5
    ports:
      - "9200:9200"
      - "9300:9200"

  ftp:
    image: bogem/ftp
    volumes:
      - "./packages/test-data:/home/vsftpd"
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
    environment:
      - FTP_USER=testuser
      - FTP_PASS=testpass
      - PASV_ADDRESS=127.0.0.1

  http:
    image: centos/httpd
    ports:
      - "8080:80"
    volumes:
      - "./packages/test-data:/var/www/html"

