version: '2'
services:
  local:
    image: bogem/ftp
    volumes:
      - "./packages/test-data:/home/vsftpd"
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
    environment:
      - FTP_USER=testuser
      - FTP_PASS=testpass
      - PASV_ADDRESS=127.0.0.1
    depends_on:
      - http
      - sftp

  http:
    image: centos/httpd
    ports:
      - "3030:80"
    volumes:
      - "./.tmp-test-data:/var/www/html:ro"

  sftp:
    image: atmoz/sftp
    ports:
      - "2222:22"
    volumes:
      - "./.tmp-test-data:/home/user/test-data:ro"
    command: user:password
