version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10
    working_directory: ~/cumulus
    steps:
      - checkout

      - run:
          name: Installing Dependencies
          command: |
            sudo yarn global add lerna
            yarn install
            yarn ybootstrap

      - run:
          name: Running Test
          command: |
            yarn test
