version: 2

jobs:
  build_and_test:
    docker:
      - image: circleci/node:6.10
      - name: localstack
        image: localstack/localstack
    working_directory: ~/project
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "lerna.json" }}-{{ checksum "package.json" }}
            - dependencies-

      - restore_cache:
          keys:
            - build-{{ checksum "lerna.json" }}-{{ checksum "package.json" }}
            - build-

      - run:
          name: Installing Dependencies
          command: |
            yarn install
            yarn ybootstrap

      - save_cache:
          paths:
            - ./node_modules
            - ./cumulus/tasks/discover-pdr/node_modules
            - ./cumulus/tasks/discover-pdrs/node_modules
            - ./cumulus/tasks/discover-granules/node_modules
            - ./cumulus/tasks/discover-s3-granules/node_modules
            - ./cumulus/tasks/hello-world/node_modules
            - ./cumulus/tasks/parse-pdr/node_modules
            - ./cumulus/tasks/pdr-status-check/node_modules
            - ./cumulus/tasks/post-to-cmr/node_modules
            - ./cumulus/tasks/queue-granules/node_modules
            - ./cumulus/tasks/queue-pdrs/node_modules
            - ./cumulus/tasks/run-gdal/node_modules
            - ./cumulus/tasks/sync-granule/node_modules
            - ./cumulus/gibs-ops-api/node_modules
            - ./cumulus/packages/api/node_modules
            - ./cumulus/packages/cmrjs/node_modules
            - ./cumulus/packages/common/node_modules
            - ./cumulus/packages/pvl/node_modules
            - ./cumulus/packages/ingest/node_modules
            - ./cumulus/packages/deployment/node_modules
            - ./cumulus/packages/sled/node_modules
          keys: dependencies-{{ checksum "lerna.json" }}-{{ checksum "package.json" }}


      - save_cache:
          paths:
            - ./cumulus/tasks/discover-pdr/dist
            - ./cumulus/tasks/discover-pdrs/dist
            - ./cumulus/tasks/discover-granules/dist
            - ./cumulus/tasks/discover-s3-granules/dist
            - ./cumulus/tasks/hello-world/dist
            - ./cumulus/tasks/parse-pdr/dist
            - ./cumulus/tasks/pdr-status-check/dist
            - ./cumulus/tasks/post-to-cmr/dist
            - ./cumulus/tasks/queue-granules/dist
            - ./cumulus/tasks/queue-pdrs/dist
            - ./cumulus/tasks/run-gdal/dist
            - ./cumulus/tasks/sync-granule/dist
            - ./cumulus/gibs-ops-api/dist
            - ./cumulus/packages/api/dist
            - ./cumulus/packages/cmrjs/dist
            - ./cumulus/packages/common/dist
            - ./cumulus/packages/pvl/dist
            - ./cumulus/packages/ingest/dist
            - ./cumulus/packages/deployment/dist
            - ./cumulus/packages/sled/dist

          key: build-{{ checksum "lerna.json" }}-{{ checksum "package.json" }}

      - run:
          name: Running Test
          environment:
            LOCALSTACK_HOST: localstack
          command: yarn test

  build_and_publish:
    docker:
      - image: circleci/node:6.10
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            yarn install
      - run:
          name: Publishing to NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            VERSION=$(cat lerna.json | jq .version --raw-output)
            ./node_modules/.bin/lerna publish --skip-git --repo-version $VERSION --yes

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      - build_and_publish:
          requires:
            - build_and_test
          filters:
            branches:
              only: message-updates