version: 2

jobs:
  build_and_test:
    docker:
      - image: circleci/node:6.10
      - name: localstack
        image: localstack/localstack
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: |
            yarn install
            yarn ybootstrap
      - run:
          name: Running Test
          environment:
            LOCALSTACK_HOST: localstack
          command: yarn test

  build_and_publish:
    docker:
      - image: circleci/node:6.10
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            yarn install
      - run:
          name: Publishing to NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            VERSION=$(cat lerna.json | jq .version --raw-output)
            ./node_modules/.bin/lerna publish --skip-git --repo-version $VERSION --yes

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      - build_and_publish:
          requires:
            - build_and_test
          filters:
            branches:
              only: CUMULUS-185 