version: 2

jobs:
  build_and_test:
    docker:
      - image: cumuluss/circleci:node-6.10
      - name: localstack
        image: localstack/localstack
    working_directory: ~/project
    steps:
      - checkout

      - restore_cache:
          keys:
            - core-{{ checksum "lerna.json" }}-{{ checksum "package.json" }}
            - core-

      - run:
          name: core installation 
          command: |
            yarn install

            # generate global hash
            ./node_modules/.bin/lerna exec --concurrency 1 -- sha1sum package.json | awk '{print $1}' '' >> /home/circleci/project/global-hash 

      - save_cache:
          paths:
            - ./node_modules
          key: core-{{ checksum "lerna.json" }}-{{ checksum "package.json" }}

      - restore_cache:
          keys:
            - packages-{{ checksum "global-hash" }}
            - cumulus-tasks-{{ checksum "global-hash" }}
            - gitc-tasks-{{ checksum "global-hash" }}
            - services-{{ checksum "global-hash" }}

      - run:
          name: Installing Dependencies
          command: |
            # start ftp
            sudo rm -rf /home/vsftpd
            sudo ln -s /home/circleci/project/packages/test-data /home/vsftpd
            sudo service vsftpd start || true

            # start http service
            sudo rm -rf /var/www/html
            sudo ln -s /home/circleci/project/.tmp-test-data /var/www/html
            sudo service apache2 start

            # start sftp service
            sudo bash /usr/sbin/sftp.sh user:password
            sudo cp -r /home/circleci/project/packages/test-data/* /home/user/

            yarn bootstrap-no-build

      - save_cache:
          paths:
            - ./packages/deployment/node_modules
            - ./packages/pvl/node_modules
            - ./packages/test-data/node_modules
            - ./packages/api/node_modules
            - ./packages/common/node_modules
            - ./packages/cmrjs/node_modules
            - ./packages/ingest/node_modules
            - ./packages/integration-tests/node_modules
            - ./packages/task-debug/node_modules
          key: packages-{{ checksum "global-hash" }}

      - save_cache:
          paths:
            - ./cumulus/tasks/hello-world/node_modules
            - ./cumulus/tasks/discover-granules/node_modules
            - ./cumulus/tasks/discover-pdrs/node_modules
            - ./cumulus/tasks/parse-pdr/node_modules
            - ./cumulus/tasks/post-to-cmr/node_modules
            - ./cumulus/tasks/pdr-status-check/node_modules
            - ./cumulus/tasks/queue-granules/node_modules
            - ./cumulus/tasks/queue-pdrs/node_modules
            - ./cumulus/tasks/sync-granule/node_modules
            - ./cumulus/tasks/discover-s3-granules/node_modules
          key: cumulus-tasks-{{ checksum "global-hash" }}

      - save_cache:
          paths:
            - ./cumulus/tasks/copy-idx-from-s3-to-efs/node_modules
            - ./cumulus/tasks/delete-ingest-tracking-data/node_modules
            - ./cumulus/tasks/delete-pdr-ftp/node_modules
            - ./cumulus/tasks/delete-pdr-s3/node_modules
            - ./cumulus/tasks/discover-cmr-granules/node_modules
            - ./cumulus/tasks/discover-http-tiles/node_modules
            - ./cumulus/tasks/dowload-activity-mock/node_modules
            - ./cumulus/tasks/filter-payload/node_modules
            - ./cumulus/tasks/generate-mrf/node_modules
            - ./cumulus/tasks/generate-pan/node_modules
            - ./cumulus/tasks/generate-pdrd/node_modules
            - ./cumulus/tasks/run-gdal/node_modules
            - ./cumulus/tasks/sync-http-urls/node_modules
            - ./cumulus/tasks/sync-wms/node_modules
            - ./cumulus/tasks/tee/node_modules
            - ./cumulus/tasks/trigger-ingest/node_modules
            - ./cumulus/tasks/trigger-mrf-gen/node_modules
            - ./cumulus/tasks/trigger-process-pdrs/node_modules
            - ./cumulus/tasks/validate-archives/node_modules
            - ./cumulus/tasks/discover-pdr/node_modules
            - ./cumulus/tasks/generate-pdr-file-list/node_modules
            - ./cumulus/tasks/validate-pdr/node_modules
          key: gitc-tasks-{{ checksum "global-hash" }}
      
      - save_cache:
          paths:
            - ./cumulus/services/sfn-scheduler/node_modules
            - ./cumulus/services/sfn-throttler/node_modules
          key: services-{{ checksum "global-hash" }}

      - run:
          name: Running Test
          environment:
            LOCALSTACK_HOST: localstack
          command: yarn test

  build_and_publish:
    docker:
      - image: circleci/node:6.10
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            yarn install

            # short fix for deployment package missing dependencies during deploy
            cd packages/deployment
            npm install
            cd ~/project

      - run:
          name: Publishing to NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            VERSION=$(cat lerna.json | jq .version --raw-output)
            ./node_modules/.bin/lerna publish --skip-git --repo-version $VERSION --yes --force-publish=*

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      - build_and_publish:
          requires:
            - build_and_test
          filters:
            branches:
              only: master 