
ApiDistribution:
  handler: index.distribution
  timeout: 20
  memory: 256
  source: 'node_modules/@cumulus/api/dist/'
  apiRole: true
  urs: true
  envs:
    EARTHDATA_BASE_URL: '{{parent.urs_url}}' 
    EARTHDATA_CLIENT_ID: '{{EARTHDATA_CLIENT_ID}}'
    EARTHDATA_CLIENT_PASSWORD: '{{EARTHDATA_CLIENT_PASSWORD}}'
    protected: '{{parent.buckets.protected.name}}'
  apiGateway:
    - api: distribution
      path: 'redirect'
      method: get
    - api: distribution
      path: '{granuleId}'
      method: get