sqs2sf:
  handler: index.starter
  timeout: 200
  memory: 512
  source: 'node_modules/@cumulus/api/dist/'

sns2elasticsearch:
  handler: index.indexer
  timeout: 100
  useElasticSearch: '{{es.name}}'
  memory: 512
  source: 'node_modules/@cumulus/api/dist/'
  tables:
    - GranulesTable
    - ExecutionsTable
    - PdrsTable
  namedLambdaDeadLetterQueue: true

log2elasticsearch:
  handler: index.logHandler
  timeout: 100
  memory: 512
  useElasticSearch: '{{es.name}}'
  source: 'node_modules/@cumulus/api/dist/'
  namedLambdaDeadLetterQueue: true

dbIndexer:
  handler: index.dbIndexer
  timeout: 300
  memory: 512
  source: 'node_modules/@cumulus/api/dist/'
  useElasticSearch: '{{es.name}}'
  tables:
    - FilesTable
  envs:
    system_bucket: '{{system_bucket}}'
  namedLambdaDeadLetterQueue: true

fallbackConsumer:
  handler: index.messageConsumer
  timeout: 100
  memory: 512
  source: 'node_modules/@cumulus/api/dist/'
  deadletterqueue: kinesisFailure
  tables:
    - RulesTable
    - CollectionsTable
    - ProvidersTable
  envs:
    system_bucket: '{{system_bucket}}'

jobs:
  handler: index.jobs
  timeout: 300
  memory: 512
  useElasticSearch: '{{es.name}}'
  source: 'node_modules/@cumulus/api/dist/'
  namedLambdaDeadLetterQueue: true

cleanExecutions:
  handler: index.cleanExecutions
  timeout: 900
  memory: 1024
  source: 'node_modules/@cumulus/api/dist/'
  namedLambdaDeadLetterQueue: true
  tables:
    - ExecutionsTable
  envs:
    nonCompleteExecutionPayloadTimeout: '"{{non_complete_execution_payload_timeout}}"'
    completeExecutionPayloadTimeout: '"{{complete_execution_payload_timeout}}"'
    nonCompleteExecutionPayloadTimeoutDisable: '"{{non_complete_execution_payload_disable}}"'
    completeExecutionPayloadTimeoutDisable: '"{{complete_execution_payload_disable}}"'

# used as custom resource for cloudformation manipulation
CustomBootstrap:
  handler: index.bootstrap
  timeout: 300
  memory: 512
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    system_bucket: '{{system_bucket}}'

EmsReport:
  handler: index.emsReport
  timeout: 300
  memory: 512
  source: 'node_modules/@cumulus/api/dist/'
  useElasticSearch: '{{es.name}}'
  envs:
    system_bucket: '{{system_bucket}}'
    ems_provider: '{{ems.provider}}'
  namedLambdaDeadLetterQueue: true

EmsDistributionReport:
  handler: index.emsDistributionReport
  timeout: 300
  memory: 512
  source: 'node_modules/@cumulus/api/dist/'
  envs:
    LOGS_BUCKET: '{{system_bucket}}'
    REPORTS_BUCKET: '{{system_bucket}}'
    STACK_NAME: '{{stackName}}'
