AccessTokensTable:
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: accessToken
      type: S
      schema: HASH

CollectionsTable:
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: name
      type: S
      schema: HASH
    - name: version
      type: S
      schema: RANGE

ProvidersTable:
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: id
      type: S
      schema: HASH

RulesTable:
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: name
      type: S
      schema: HASH

UsersTable:
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: userName
      type: S
      schema: HASH

GranulesTable:
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: granuleId
      type: S
      schema: HASH

PdrsTable:
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: pdrName
      type: S
      schema: HASH


ExecutionsTable:
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: arn
      type: S
      schema: HASH

FilesTable:
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: bucket
      type: S
      schema: HASH
    - name: key
      type: S
      schema: RANGE

AsyncOperationsTable:
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: id
      type: S
      schema: HASH
