CollectionsTable:
  read: 5
  write: 1
  pointInTime: '{{tables.enablePointInTime}}'
  enableAutoScaling: '{{tables.collections.enableAutoScaling}}'
  autoScaling:
    roleArn: '{{iams.scalingRoleArn}}'
    writeCapacityUnits:
      min: '{{tables.collections.autoScaling.writeCapacityUnits.min}}'
      max: '{{tables.collections.autoScaling.writeCapacityUnits.max}}'
    policyConfiguration:
      targetValue: '{{tables.collections.autoScaling.policyConfiguration.targetValue}}'
      scaleInCooldown: '{{tables.collections.autoScaling.policyConfiguration.scaleInCooldown}}'
      scaleOutCooldown: '{{tables.collections.autoScaling.policyConfiguration.scaleOutCooldown}}'
  attributes:
    - name: name
      type: S
      schema: HASH
    - name: version
      type: S
      schema: RANGE

ProvidersTable:
  read: 5
  write: 1
  pointInTime: '{{tables.enablePointInTime}}'
  attributes:
    - name: id
      type: S
      schema: HASH

RulesTable:
  read: 5
  write: 1
  pointInTime: '{{tables.enablePointInTime}}'
  attributes:
    - name: name
      type: S
      schema: HASH

UsersTable:
  read: 5
  write: 1
  pointInTime: '{{tables.enablePointInTime}}'
  attributes:
    - name: userName
      type: S
      schema: HASH

GranulesTable:
  read: 5
  write: 10
  pointInTime: '{{tables.enablePointInTime}}'
  attributes:
    - name: granuleId
      type: S
      schema: HASH

PdrsTable:
  read: 5
  write: 2
  pointInTime: '{{tables.enablePointInTime}}'
  attributes:
    - name: pdrName
      type: S
      schema: HASH


ExecutionsTable:
  read: 5
  write: 10
  pointInTime: '{{tables.enablePointInTime}}'
  attributes:
    - name: arn
      type: S
      schema: HASH

FilesTable:
  read: 5
  write: 10
  pointInTime: '{{tables.enablePointInTime}}'
  attributes:
    - name: bucket
      type: S
      schema: HASH
    - name: key
      type: S
      schema: RANGE
