sf2snsStart:
  handler: index.start
  timeout: 100
  memory: 128
  source: 'node_modules/@cumulus/api/dist/sfSnsBroadcast/'

sf2snsEnd:
  handler: index.end
  timeout: 100
  memory: 128
  source: 'node_modules/@cumulus/api/dist/sfSnsBroadcast/'
