default:
  stackName: change-me-cumulus
  stackNameNoDash: ChangeMeCumulus

  urs_url: https://uat.urs.earthdata.nasa.gov

  repo_owner: cumulus-nasa
  message_adapter_repo: cumulus-message-adapter
  message_adapter_filename: cumulus-message-adapter.zip

  nested_templates:
    CumulusApiDefault:
      cfFile: node_modules/@cumulus/deployment/app/cumulus_api.template.yml
      configFile: node_modules/@cumulus/deployment/app/cumulus_api_default.config.yml
    CumulusApiV1:
      cfFile: node_modules/@cumulus/deployment/app/cumulus_api.template.yml
      configFile: node_modules/@cumulus/deployment/app/cumulus_api_v1.config.yml

  # if not specified the value of the apigatewy backend endpoint is used
  # api_backend_url: https://apigateway-url-to-api-backend/

  # if not specified the value of the apigateway dist url is used
  # api_distribution_url: https://apigateway-url-to-distribution-app/

  params:
    - name: CmrPassword
      value: '{{CMR_PASSWORD}}' # this has to be set in .env

  shared_data_bucket: 'cumulus-data-shared'

  buckets:
    internal: change-me
    private: change-me
    protected: change-me
    public: change-me

  cmr:
    username: devseed
    provider: CUMULUS
    clientId: CUMULUS
    password: '{{CMR_PASSWORD}}'
  
  ems:
    provider: CUMULUS

  # this whole section has to be updated in each deployment section
  vpc:
    vpcId: xxxxxx #change-me
    subnets:
      - subnet-xxxxx #change me

  default_users:
    aimeeb: true
    jennyhliu: true
    jnorton1: true
    kbaynes: true
    kkelly: true
    lfrederick: true
    mhuffnagle2: true
    pquinn1: true
    scisco: true
    sethvincent: true

  ecs:
    restartTasksOnDeploy: false
    amiid: ami-6944c513
    instanceType: change-me 
    volumeSize: 50
    availabilityZone: 'us-east-1a'
    maxInstances: 1
    desiredInstances: 0

  es:
    name: es5
    elasticSearchMapping: 5
    version: 5.3
    instanceCount: 1
    instanceType: t2.small.elasticsearch
    volumeSize: 35

  # defining the APIs. Each item will include a separate endpoint
  apiStage: dev

  dynamos:
    CollectionsTable:
      read: 5
      write: 1
      attributes:
        - name: name
          type: S
          schema: HASH
        - name: version
          type: S
          schema: RANGE

    ProvidersTable:
      read: 5
      write: 1
      attributes:
        - name: id
          type: S
          schema: HASH

    RulesTable:
      read: 5
      write: 1
      attributes:
        - name: name
          type: S
          schema: HASH

    UsersTable:
      read: 5
      write: 1
      attributes:
        - name: userName
          type: S
          schema: HASH

  sns:
    # this topic receives all the updates from
    # step functions
    sftracker:
      subscriptions:
        lambda:
          endpoint:
            function: Fn::GetAtt
            array:
              - sns2elasticsearchLambdaFunction
              - Arn

  apis:
    - name: distribution
    - name: backend

  sqs:
    startSF:
      visibilityTimeout: 20
      retry: 30
      consumer:
        - lambda: sqs2sf
          schedule: rate(1 minute)
          messageLimit: 10
          state: ENABLED

  rules:
    backgroundJobs:
      schedule: rate(10 minutes)
      state: ENABLED
      targets:
        - lambda: jobs
    cronJobs:
      # run at 5:00am GMT daily
      schedule: cron(0 5 * * ? *)
      state: ENABLED
      targets:
        - lambda: EmsReport

  stepFunctions: !!files ['workflows.yml']

  lambdas: !!files [
    'lambdas.yml',
    'node_modules/@cumulus/api/config/lambdas.yml']
