default:

  apiDeploy: true
  dynamo2ElasticSearch:
    batchSize: 10
    startingPosition: TRIM_HORIZON
    lambda: dbIndexer
    tables:
      - CollectionsTable
      - RulesTable
      - ProvidersTable
      - GranulesTable
      - PdrsTable
      - ExecutionsTable

  apis:
    - name: distribution
    - name: backend

  lambdas: !!files [
    'node_modules/@cumulus/api/config/distribution.yml',
    'node_modules/@cumulus/api/config/api_default.yml'
  ]