default:
  customCompilation: true
  oldLambdaInjection: true
  lambdaProcess: true
  useWorkflowLambdaVersions: true
  lambdas: !!files [
  'lambdas.yml',
  'node_modules/@cumulus/api/config/lambdas.yml']

  repo_owner: nasa
  message_adapter_repo: cumulus-message-adapter
  message_adapter_filename: cumulus-message-adapter.zip
