default:
  prefix: test-cumulus-integration
  stackName: test-cumulus-integration-deployer
  prefixNoDash: testCumulusIntgDeployer
  buckets:
    internal: cumulus-test-sandbox-internal
  capabilities:
    - CAPABILITY_IAM

  params:
    - name: Prefix
      value: '{{prefix}}'
    - name: StateMachinePrefix
      value: '{{prefixNoDash}}'
    - name: InternalBucketName
      value: '{{buckets.internal}}'

mth-cum-test:
  prefix: mth-cum-test
  stackName: '{{prefix}}-deployer'
  prefixNoDash: mthCumTestDeployer
  buckets:
    internal: '{{prefix}}-internal'

jl:
  prefix: jl-test-integration
  stackName: jl-test-integration-deployer
  prefixNoDash: jlTestIntgDeployer

