default:

  vpc:
    vpcId: '{{VPC_ID}}'         # this has to be set in .env
    subnets:
      - '{{AWS_SUBNET}}'        # this has to be set in .env
    cidrIp: '{{VPC_CIDR_IP}}'   # this has to be set in .env

  dynamos: !!files ['node_modules/@cumulus/api/config/tables.yml']

  es:
    name: es5vpc
    elasticSearchMapping: 8
    version: 5.3
    instanceCount: 1
    instanceType: t2.small.elasticsearch
    volumeSize: 35
    alarms:
      NodesLow:
        alarm_description: 'There are less instances running than the desired'
        comparison_operator: LessThanThreshold
        threshold: '{{es.instanceCount}}'
        metric: Nodes
