Parameters:
  StateMachinePrefix:
    Type: String
    Description: An alphanumeric string used to prefix State Machine names

Resources:
  Fn:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Join ['-', [!Ref StackName, task, !Var name]]
      Description: 'Runs scheduled discovery / ingest'
      Runtime: nodejs6.10
      Code: !Var path
      Timeout: 300
      MemorySize: 256
      Handler: index.handler
      Role: !GetAtt [TaskExecutionRole, Arn]

  Service:
    DependsOn:
      - !ResourceName Fn
    Properties:
      DesiredCount: 1

  Task:
    Properties:
      ContainerDefinitions:
      - Command:
        - !GetAtt [!ResourceName Fn, Arn]
        - "--eventJson"
        - !Sub >-
          {
            "resources": {
              "stack": "${AWS::StackName}",
              "state_machine_prefix": "${StateMachinePrefix}",
              "buckets": {
                "config": "${ConfigS3Bucket}",
                "private": "${PrivateBucketName}",
                "public": "${PublicBucketName}"
              },
              "tables": {
                "connections": "${StackName}-connects",
                "locks": "${StackName}-locks"
              }
            },
            "payload": {"Key": "ingest/collections.yml", "Bucket": "${ConfigS3Bucket}"}
          }
