default:
  prefix: test-cumulus-integration
  stackName: '{{prefix}}-iam'
  authorizor: false
  capabilities:
    - CAPABILITY_NAMED_IAM

  system_bucket: cumulus-test-sandbox-internal

  buckets:
    - key: internal 
      name: cumulus-test-sandbox-internal
      type: internal
    - key: private
      name: cumulus-test-sandbox-private
      type: private
    - key: protected
      name: cumulus-test-sandbox-protected
      type: protected
    - key: public
      name: cumulus-test-sandbox-public
      type: public
    - key: public-2
      name: cumulus-test-sandbox-public-2
      type: public
    - key: shared
      name: cumulus-data-shared
      type: shared

  params:
     - name: ResourcePrefix
       value: '{{prefix}}'

cumulus-from-npm:
  prefix: test-npm-integration

cumulus-from-source:
  prefix: test-src-integration

lf: 
  prefix: lf-cumulus
  stackName: lf-cumulus-iam