default:
  prefix: test-cumulus-integration
  stackName: '{{prefix}}-iam'
  authorizor: false
  capabilities:
    - CAPABILITY_NAMED_IAM

  system_bucket: cumulus-test-sandbox-internal

  buckets:
    internal: 
      name: cumulus-test-sandbox-internal
      type: internal
    private:
      name: cumulus-test-sandbox-private
      type: private
    protected:
      name: cumulus-test-sandbox-protected
      type: protected
    public:
      name: cumulus-test-sandbox-public
      type: public
    protected-2:
      name: cumulus-test-sandbox-protected-2
      type: protected
    shared:
      name: cumulus-data-shared
      type: shared

  params:
     - name: ResourcePrefix
       value: '{{prefix}}'

cumulus-from-npm:
  prefix: test-npm-integration

cumulus-from-source:
  prefix: test-src-integration

lf: 
  prefix: lf-cumulus
  stackName: lf-cumulus-iam