
default:
  prefix: change-me 
  stackName: '{{prefix}}-integration'
  # stackNameNoDash: TestCumulusIntegration
  shared_data_bucket: cumulus-data-shared
  api_distribution_url: https://example.com/
  params:
    - name: CmrPassword
      value: '{{CMR_PASSWORD}}'
    - name: DockerEmail
      value: '{{DOCKER_EMAIL}}'
    - name: DockerPassword
      value: '{{DOCKER_PASS}}'

  apiStage: dev

  vpc:
    vpcId: '{{VPC_ID}}' 
    subnets:
      - '{{AWS_SUBNET}}'

  ecs:
    instanceType: t2.small
    desiredInstances: 1
    availabilityZone: us-east-1b
    amiid: ami-a7a242da
    publicIp: true
    restartTasksOnDeploy: true
    docker:
      username: cumulususer
    services:
      EcsTaskHelloWorld:
        image: cumuluss/cumulus-ecs-task:1.1.1
        cpu: 400
        memory: 700
        count: 1
        envs:
          AWS_DEFAULT_REGION:
            function: Fn::Sub
            value: '${AWS::Region}'
        commands:
          - cumulus-ecs-task
          - '--activityArn'
          - function: Ref
            value: EcsTaskHelloWorldActivity
          - '--lambdaArn'
          - function: Ref
            value: HelloWorldLambdaFunction

  activities:
    - name: EcsTaskHelloWorld

  system_bucket: cumulus-test-sandbox-internal

  buckets:
    internal: cumulus-test-sandbox-internal
    private: cumulus-test-sandbox-private
    protected: cumulus-test-sandbox-protected
    public: cumulus-test-sandbox-public

  cmr:
    username: '{{CMR_USERNAME}}'
    provider: CUMULUS
    clientId: CUMULUS
    password: '{{CMR_PASSWORD}}'

  iams:
    ecsRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{prefix}}-integration-ecs'
    lambdaApiGatewayRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{prefix}}-integration-lambda-api-gateway'
    lambdaProcessingRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{prefix}}-integration-lambda-processing'
    stepRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{prefix}}-integration-steprole'
    instanceProfile: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:instance-profile/{{prefix}}-integration-ecs'

  sns:
    inregions3:
      subscriptions:
        lambda:
          endpoint:
            function: Fn::GetAtt
            array:
              - InRegionS3PolicyLambdaFunction
              - Arn
    AmazonIpSpaceChanged:
      arn: arn:aws:sns:us-east-1:806199016981:AmazonIpSpaceChanged
      subscriptions:
        lambda:
          endpoint:
            function: Fn::GetAtt
            array:
              - InRegionS3PolicyLambdaFunction
              - Arn

  urs_url: https://uat.urs.earthdata.nasa.gov/ #make sure to include the trailing slash

    # if not specified the value of the apigateway backend endpoint is used
    # api_backend_url: https://apigateway-url-to-api-backend/ #make sure to include the trailing slash

    # if not specified the value of the apigateway dist url is used
    # api_distribution_url: https://apigateway-url-to-distribution-app/ #make sure to include the trailing slash

  # URS users who should have access to the dashboard application.
  users:
    - username: testuser

cumulus-from-npm:
  prefix: test-npm # used by the integration repo
  stackNameNoDash: TestNpmIntegration

cumulus-from-source:
  prefix: test-src # used by the cumulus repo
  stackNameNoDash: TestSourceIntegration

aj:
  prefix: aj
  stackNameNoDash: AjIntegration

lf:
  stackName: lf-cumulus
  stackNameNoDash: lfCumulus

  es: 
    elasticSearchMapping: 7

  iams:
    ecsRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/lf-cumulus-ecs'
    lambdaApiGatewayRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/lf-cumulus-lambda-api-gateway'
    lambdaProcessingRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/lf-cumulus-lambda-processing'
    stepRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/lf-cumulus-steprole'
    instanceProfile: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:instance-profile/lf-cumulus-ecs'
