Resources:

  # EcsTaskHelloWorld service autoscaling

  EcsTaskHelloWorldECSServiceScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: 1
      MaxCapacity: 10
      ResourceId:
        Fn::Sub:
          - service/${CumulusECSCluster}/${ServiceName}
          - ServiceName:
              Fn::GetAtt:
                - "EcsTaskHelloWorldECSService"
                - Name
      RoleARN: {{iams.scalingRoleArn}}
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  # EcsTaskHelloWorld service autoscaling in

  EcsTaskHelloWorldECSServiceScalingInPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn:
      - EcsTaskHelloWorldECSServiceScalableTarget
    Properties:
      PolicyName: {{prefix}}EcsTaskHelloWorldECSServiceScalingInPolicy
      PolicyType: StepScaling
      ScalingTargetId:
        Ref:
         EcsTaskHelloWorldECSServiceScalableTarget
      StepScalingPolicyConfiguration:
        Cooldown: 60
        AdjustmentType: PercentChangeInCapacity
        MinAdjustmentMagnitude: 1
        StepAdjustments:
          - MetricIntervalUpperBound: 0
            ScalingAdjustment: -5

  EcsTaskHelloWorldECSServiceScalingInAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Ref: EcsTaskHelloWorldECSServiceScalingInPolicy
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Metrics:
        - Id: e1
          Expression: "FILL(m1, 0)"
          Label: NormalizedActivityScheduleTime
        - Id: m1
          MetricStat:
            Metric:
              Namespace: AWS/States
              MetricName: ActivityScheduleTime
              Dimensions:
                - Name: ActivityArn
                  Value:
                    Ref:
                      EcsTaskHelloWorldActivity
            Period: 60
            Stat: Average
          ReturnData: false
      ComparisonOperator: LessThanThreshold
      Threshold: 5000
      TreatMissingData: missing

  # EcsTaskHelloWorld service autoscaling out

  EcsTaskHelloWorldECSServiceScalingOutPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: {{prefix}}EcsTaskHelloWorldECSServiceScalingOutPolicy
      PolicyType: StepScaling
      ScalingTargetId:
        Ref:
         EcsTaskHelloWorldECSServiceScalableTarget
      StepScalingPolicyConfiguration:
        Cooldown: 60
        AdjustmentType: PercentChangeInCapacity
        MinAdjustmentMagnitude: 1
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            ScalingAdjustment: 10

  EcsTaskHelloWorldECSServiceScalingOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Ref: EcsTaskHelloWorldECSServiceScalingOutPolicy
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Metrics:
        - Id: e1
          Expression: "FILL(m1, 0)"
          Label: NormalizedActivityScheduleTime
        - Id: m1
          MetricStat:
            Metric:
              Namespace: AWS/States
              MetricName: ActivityScheduleTime
              Dimensions:
                - Name: ActivityArn
                  Value:
                    Ref:
                      EcsTaskHelloWorldActivity
            Period: 60
            Stat: Average
          ReturnData: false
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 10000
      TreatMissingData: missing

  # EcsTaskHelloWorldKesCma service autoscaling

  EcsTaskHelloWorldKesCmaECSServiceScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: 1
      MaxCapacity: 10
      ResourceId:
        Fn::Sub:
          - service/${CumulusECSCluster}/${ServiceName}
          - ServiceName:
              Fn::GetAtt:
                - "EcsTaskHelloWorldKesCmaECSService"
                - Name
      RoleARN: {{iams.scalingRoleArn}}
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  # EcsTaskHelloWorldKesCma service autoscaling in

  EcsTaskHelloWorldKesCmaECSServiceScalingInPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn:
      - EcsTaskHelloWorldKesCmaECSServiceScalableTarget
    Properties:
      PolicyName: {{prefix}}EcsTaskHelloWorldKesCmaECSServiceScalingInPolicy
      PolicyType: StepScaling
      ScalingTargetId:
        Ref:
         EcsTaskHelloWorldKesCmaECSServiceScalableTarget
      StepScalingPolicyConfiguration:
        Cooldown: 60
        AdjustmentType: PercentChangeInCapacity
        MinAdjustmentMagnitude: 1
        StepAdjustments:
          - MetricIntervalUpperBound: 0
            ScalingAdjustment: -5

  EcsTaskHelloWorldKesCmaECSServiceScalingInAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Ref: EcsTaskHelloWorldKesCmaECSServiceScalingInPolicy
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Metrics:
        - Id: e1
          Expression: "FILL(m1, 0)"
          Label: NormalizedActivityScheduleTime
        - Id: m1
          MetricStat:
            Metric:
              Namespace: AWS/States
              MetricName: ActivityScheduleTime
              Dimensions:
                - Name: ActivityArn
                  Value:
                    Ref:
                      EcsTaskHelloWorldKesCmaActivity
            Period: 60
            Stat: Average
          ReturnData: false
      ComparisonOperator: LessThanThreshold
      Threshold: 5000
      TreatMissingData: missing

  # EcsTaskHelloWorldKesCma service autoscaling out

  EcsTaskHelloWorldKesCmaECSServiceScalingOutPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: {{prefix}}EcsTaskHelloWorldKesCmaECSServiceScalingOutPolicy
      PolicyType: StepScaling
      ScalingTargetId:
        Ref:
         EcsTaskHelloWorldKesCmaECSServiceScalableTarget
      StepScalingPolicyConfiguration:
        Cooldown: 60
        AdjustmentType: PercentChangeInCapacity
        MinAdjustmentMagnitude: 1
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            ScalingAdjustment: 10

  EcsTaskHelloWorldKesCmaECSServiceScalingOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Ref: EcsTaskHelloWorldKesCmaECSServiceScalingOutPolicy
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Metrics:
        - Id: e1
          Expression: "FILL(m1, 0)"
          Label: NormalizedActivityScheduleTime
        - Id: m1
          MetricStat:
            Metric:
              Namespace: AWS/States
              MetricName: ActivityScheduleTime
              Dimensions:
                - Name: ActivityArn
                  Value:
                    Ref:
                      EcsTaskHelloWorldKesCmaActivity
            Period: 60
            Stat: Average
          ReturnData: false
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 10000
      TreatMissingData: missing
