Parameters:
  StateMachinePrefix:
    Type: String
    Description: An alphanumeric string used to prefix State Machine names

Resources:
  Fn:
    Properties:
      Description: 'Runs scheduled discovery / ingest'
      Runtime: nodejs6.10

  Service:
    Properties:
      DesiredCount: 1

  Task:
    Properties:
      ContainerDefinitions:
      - Command:
        - !GetAtt [!ResourceName Fn, Arn]
        - "--eventJson"
        - !Sub >-
          {
            "resources": {
              "stack": "${AWS::StackName}",
              "state_machine_prefix": "${StateMachinePrefix}",
              "buckets": {
                "config": "${ConfigS3Bucket}",
                "private": "${StackName}-private",
                "public": "${StackName}-public"
              },
              "tables": {
                "connections": "${StackName}-connects",
                "locks": "${StackName}-locks"
              }
            },
            "payload": {"Key": "ingest/collections.yml", "Bucket": "${ConfigS3Bucket}"}
          }
