<cumulus-deployment-name>:
  prefix: <prefix>-cumulus         # stackName must match the prefix for your IAM stack
  prefixNoDash: <Prefix>Cumulus

  apiStage: dev

  vpc:
    vpcId: '{{VPC_ID}}'         # this has to be set in .env
    subnets:
      - '{{AWS_SUBNET}}'        # this has to be set in .env
    cidrIp: '{{VPC_CIDR_IP}}'   # this has to be set in .env

  ecs:
    instanceType: t2.micro
    desiredInstances: 0
    availabilityZone: <subnet-id-zone>
    amiid: <some-ami-id>

  buckets:
    internal:
      name: <prefix>-internal
      type: internal
    private:
      name: <prefix>-private
      type: private
    protected:
      name: <prefix>-protected
      type: protected
    public:
      name: <prefix>-public
      type: public

  urs_url: https://uat.urs.earthdata.nasa.gov/ # make sure to include the trailing slash

  # if not specified the value of the apigateway backend endpoint is used
  # api_backend_url: https://apigateway-url-to-api-backend/ #make sure to include the trailing slash

  # if not specified the value of the apigateway dist url is used
  # api_distribution_url: https://apigateway-url-to-distribution-app/ #make sure to include the trailing slash

  # URS users who should have access to the dashboard application and use the
  # distribution API to access protected files.
  users:
    - username: <user>
    - username: <user2>
